### ISSUE TITLE
Picadinhos.c

### ISSUE THREAD

**Issue by htaschne** [LucasJusto/Picadinhos#1]
Reescrevendo teu programa em C fica assim:
```c
#include<stdio.h>
#include<stdlib.h>

long long int gauss(long long int i, long long int f) {
    return(i + f) * (f - i + 1) / 2;
}
int main() {
    long long int n;
    scanf("%lld", &n);
    long long int *res = malloc(sizeof(long long int) * n);
    for(long long int i = 0; i < n; i++) {
        res[i] = 0;
    }
    for(long long int i = 1; i < (n / 2) + 1; i++) {
        for(long long int j = i + 1; j < (n / 2) + 1; j++) {
            long long int result = gauss(i, j);
            if(result <= n && result > 0) {
                res[result - 1]++;
            } else {
                break;
            }
        }
    }
    long long int maior = res[0] + 1;
    long long int indice = 1;
    for(long long int k = 0; k < n; k++) {
        if(res[k] + 1 > maior) {
            maior = res[k] + 1;
            indice = k + 1;
        }
    }
    printf("%lld %lld\n", indice, maior);
    return 0;
}
```
Pelos resultados que eu tive e os que tu tinha me enviado não percebi grandes diferenças de performace. Toda via, ainda tem melhorias que podem ser feitas, como retirar a chamada do método e usar outra estrutura de dados (?). Se quiser testar no teu computador basta executar:
```
$ gcc -O3 picadinhos.c
```
Eu me animei pra tentar algumas coisas, assim que eu tiver resultados te mando.

**Comment by LucasJusto** [comment]
As unicas operações feitas sobre a estrutura de dados, são get e insert (pra atualizar e mostrar os numeros), e em vetor as 2 são O(1) (get: v[n]  insert: v[n]++). Enquanto a por a formula direto dentro do for sem metodo... acho que não afetaria muito. Boa sorte na tua tentativa e valeu pelo programa em C.
